---
name: Build

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '30 13 * * *'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 120
    strategy:
      matrix:
        os:
          - ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Build
      shell: bash
      run: |
        if [[ ${RUNNER_OS} == "Linux" ]]; then
            sudo apt-get update
            sudo apt-get install -y lib{pango1.0,x11,xext,xft,xinerama,mpv}-dev\
                lib{xcursor,xrender,xfixes,webkit2gtk-4.1,vlc,png,gl1-mesa}-dev\
                ninja-build libglu1-mesa-dev
        fi > /dev/null
        cargo build --quiet --release
    - name: Archive
      uses: actions/upload-artifact@v4
      with:
        retention-days: 1
        path: |
          target/release/lightron
          target/release/lightron-gui
